CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

CREATE TABLE IF NOT EXISTS bronze.weather_raw (
    id SERIAL PRIMARY KEY,
    source VARCHAR(50) DEFAULT 'unknown',
    extraction_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    data JSONB NOT NULL,
    processed BOOLEAN DEFAULT FALSE
);